# Read configuration file
configfile: "config/config.yaml"
SAMPLES = config["samples"]

# Define the rule that determines the final targets of the workflow
rule all:
    input:
        'results/final_output.txt'

rule quantify_genes:
    input:
        genome = 'resources/genome.fa',
        r1 = 'resources/{sample}.R1.fastq.gz',
        r2 = 'resources/{sample}.R2.fastq.gz'
    output:
        'data/{sample}.txt'
    threads: 1
    resources:
        mem_mb=1000, 
        walltime='00:01:00'
    shell:
        'echo {input.genome} {input.r1} {input.r2} > {output}'

rule collate_outputs:
    input:
        expand('data/{sample}.txt', sample=SAMPLES)
    output:
        'results/final_output.txt'
    # conda: "envs/py38.yaml"
    threads: 1
    resources:
        mem_mb=1000, 
        walltime='00:01:00'
    run:
        with open(output[0], 'w') as out:
            for i in input:
                sample = i.split('.')[0]
                for line in open(i):
                    out.write(sample + ' ' + line)

