# Read configuration file
configfile: "config/config.yaml"
SAMPLES = config["samples"]

# Define the rule that determines the final targets of the workflow
rule all:
    input:
        'results/final_output.txt'

rule quantify_genes:
    input:
        genome = 'resources/genome.fa',
        r1 = 'resources/{sample}.R1.fastq.gz',
        r2 = 'resources/{sample}.R2.fastq.gz'
    output:
        'data/{sample}.txt'
    params: 
        build = config["build"]
    threads: 2
    resources:
        mem_mb=2048, 
        time_min='00:05:00', 
    shell:
        'echo {params.build} {input.genome} {input.r1} {input.r2} > {output}'

rule collate_outputs:
    input:
        expand('data/{sample}.txt', sample=SAMPLES)
    output:
        'results/final_output.txt'
    conda: "envs/py39.yaml"
    threads: 1
    resources:
        mem_mb=2048, 
        time_min='00:05:00',
    script: 
        "scripts/collate_outputs.py"


