# config.yaml
# snakemake -j 1 -np
# snakemake -j 1 --profile sge -np
# snakemake -j 1 --profile sge --use-conda -np
# snakemake -j 1 --cluster "qsub -cwd -pe smp {threads} -l mem_free={resources.mem_mb}M -l h_rt={resources.walltime}"

samples: ['Sample1', 'Sample2']
